/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatterMatterIdRouteImport } from './routes/matter/$matterId'
import { Route as CoordinateMatterIdRouteImport } from './routes/coordinate/$matterId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatterMatterIdRoute = MatterMatterIdRouteImport.update({
  id: '/matter/$matterId',
  path: '/matter/$matterId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordinateMatterIdRoute = CoordinateMatterIdRouteImport.update({
  id: '/coordinate/$matterId',
  path: '/coordinate/$matterId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/plan': typeof PlanRoute
  '/profile': typeof ProfileRoute
  '/coordinate/$matterId': typeof CoordinateMatterIdRoute
  '/matter/$matterId': typeof MatterMatterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/plan': typeof PlanRoute
  '/profile': typeof ProfileRoute
  '/coordinate/$matterId': typeof CoordinateMatterIdRoute
  '/matter/$matterId': typeof MatterMatterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/plan': typeof PlanRoute
  '/profile': typeof ProfileRoute
  '/coordinate/$matterId': typeof CoordinateMatterIdRoute
  '/matter/$matterId': typeof MatterMatterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/plan'
    | '/profile'
    | '/coordinate/$matterId'
    | '/matter/$matterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/plan'
    | '/profile'
    | '/coordinate/$matterId'
    | '/matter/$matterId'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/plan'
    | '/profile'
    | '/coordinate/$matterId'
    | '/matter/$matterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  PlanRoute: typeof PlanRoute
  ProfileRoute: typeof ProfileRoute
  CoordinateMatterIdRoute: typeof CoordinateMatterIdRoute
  MatterMatterIdRoute: typeof MatterMatterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matter/$matterId': {
      id: '/matter/$matterId'
      path: '/matter/$matterId'
      fullPath: '/matter/$matterId'
      preLoaderRoute: typeof MatterMatterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordinate/$matterId': {
      id: '/coordinate/$matterId'
      path: '/coordinate/$matterId'
      fullPath: '/coordinate/$matterId'
      preLoaderRoute: typeof CoordinateMatterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  PlanRoute: PlanRoute,
  ProfileRoute: ProfileRoute,
  CoordinateMatterIdRoute: CoordinateMatterIdRoute,
  MatterMatterIdRoute: MatterMatterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
